M48
; DRILL file {KiCad 7.0.9} date Do 29 Feb 2024 00:37:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-29T00:37:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X70.29Y-61.892
X73.29Y-61.892
X73.745Y-47.777
X73.745Y-50.777
T2
X49.718Y-68.177
X72.642Y-68.177
T0
M30
